::: {.callout-note collapse="true"}
# Meeting 28.04.2026
Discussed priorities over the next 6 weeks:

* Scenarios & uncertainty
  + Implement at least one element of:
    -   Construction of ecosystem condition indicators/anomalies (indicator choice/weighting; baseline conditions)
    -   Alternative objective functions (total condition improvement vs area exceeding a threshold)
  + Sensitivity analysis --\> how do different formulations affect spatial patterns of selected areas and trade-offs between objectives?
* Towards WP3
  + Outline of plan to move framework towards dynamic spatial optimisation model
  + Full understanding of results

Less immediate priorities: 
* Complete implementation of 4-objective version
  + Implement simple approach but not needed to be perfect
  + Implementation of convolution-based connectivity metric
    -   speed of computation
  + How to balance decision variable (amount to rehabilitate vs convert)
  + How to include multiple cost layers
* Implementation at national scale
  + Scaling up algorithm
    -   speed of computation
    -   decisions regarding resolution of decision variable
  + Testing effect of less elaborated cost data
  + Decisions regarding resolution of decision vector, etc.
* Algorithm fine-tuning
  + Systematic runs varying algorithm parameters (population size, number of generations, mutation/crossover rates, etc.) and their influence on convergence and solution quality.
  + Sensitivity analysis to understand how robust the Pareto front is to algorithm settings (minimum = random seed).
:::
::: {.callout-note collapse="true"}
# 30.04.2026
* Updated code to improve speed but had to revert because of changes to output. Identified that this was due to threading/parallelisation making some stochasiticty in output.
:::
::: {.callout-note collapse="true"}
# Week of 04.05.2026

* Updated framework to run multiple scenarios to test different sensitivity dimensions - starting with construction of ecosystem condition indicators/anomalies (indicator choice/weighting; baseline conditions).
* Updated opt_results_comparison with initial visualisations of results across scenarios. 
* Improved speed of code - from approx 90 mins to 10 mins for KB. Previous versions were doing expensive sorting for selection of repair candidates, which was not necessary due to changes in how repair is done (mostly random selection). 

Trying to base the approach in literature

https://doi.org/10.1007/978-3-030-05252-2_2 Lambert: Robust Decision-Making

The basis used for Roman et al., 2026

X: exogenous uncertainties: 
L: Policy levers: area target, municipal burden sharing, cost constraint etc.

Roman et al., 2026 adds stochasticity. 

R: Relationships: optimisation model, objective functions, restoration response assumptions

From (https://doi.org/10.1029/2021EF002322):
"The authors of (Marchau et al., 2019) characterize different levels of uncertainty, and describe the condition of deep uncertainty. Problems are deeply uncertain when impacts analysts cannot agree on the conceptual models that could be used to represent probable futures, the probability distributions representing uncertainty of parameters in the future, and/or how to value the different outcomes.""

:::

# Meeting 12.05.2026

* Adrienne's perspective: maybe as the RFOP values are in general low, it's of course going to be impossible to identify robust areas? Many solutions, not super discriminating
Proposed several possible approaches to address this:
- Combine the abiotic & biotic anomalies into a single objective (requires identifying a reasonable other 3rd objective)

# Meeting 22/05/2026

* Looked at results of changing the objectives, new definition of 'robust' areas, but still needs some work to derive clear insights.
* Next steps: look again at the specific sensitivity dimensions - what does the spatial layout of areas that are robust to indicator construction look like? What about the areas that are sensitive to policy levers? etc. Try and draw out this difference.
* Then discussed the development of the WP3 framework - Adrienne said she understood eveything
* Ideas for framing of work (and thesis in general) - focus on the uncertainty/robustness and how this should make us question the use of models in decision making
+ Adrienne mentioned upcoming talk where she would conceptualise how science should be more reflective with policymakers - encouraging more discussion about the selected areas and the uncertainty around them, rather than just presenting a single solution.
* Go forward with DMDU summer school - Adrienne ok to support financially.
* To work on presentation for next two weeks - meet with Adrienne during writing week to discuss framing and content?